-- MySQL Script generated by MySQL Workbench
-- Sat Jul 10 09:44:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cms_s
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cms_s
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms_s` DEFAULT CHARACTER SET utf8 ;
USE `cms_s` ;

-- -----------------------------------------------------
-- Table `cms_s`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_s`.`administrador` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `clave` BLOB NOT NULL,
  `estado` INT NULL,
  `fecha_creacion` DATETIME NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms_s`.`pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_s`.`pagina` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `texto` LONGTEXT NULL,
  `foto` VARCHAR(64) NULL,
  `video` VARCHAR(64) NULL,
  `estado` INT NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `aid` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_pagina_administrador_idx` (`aid` ASC) VISIBLE,
  CONSTRAINT `fk_pagina_administrador`
    FOREIGN KEY (`aid`)
    REFERENCES `cms_s`.`administrador` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms_s`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_s`.`usuario` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `clave` BLOB NOT NULL,
  `estado` INT NULL,
  `fecha_creacion` DATETIME NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms_s`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_s`.`articulo` (
  `arid` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `texto` LONGTEXT NULL,
  `foto` VARCHAR(64) NULL,
  `categoria` VARCHAR(64) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `autor` VARCHAR(64) NOT NULL,
  `estado` INT NULL,
  `aid` INT NOT NULL,
  PRIMARY KEY (`arid`),
  INDEX `fk_articulo_administrador1_idx` (`aid` ASC) VISIBLE,
  CONSTRAINT `fk_articulo_administrador1`
    FOREIGN KEY (`aid`)
    REFERENCES `cms_s`.`administrador` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms_s`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_s`.`comentario` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(256) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `estado` INT NULL,
  `aid` INT NOT NULL,
  `usuario_uid` INT NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `fk_comentario_articulo1_idx` (`aid` ASC) VISIBLE,
  INDEX `fk_comentario_usuario1_idx` (`usuario_uid` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_articulo1`
    FOREIGN KEY (`aid`)
    REFERENCES `cms_s`.`articulo` (`arid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_uid`)
    REFERENCES `cms_s`.`usuario` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
